### ISSUE TITLE
Investigate difficulties importing package from Jupyter Notebooks

### ISSUE THREAD

**Issue by ViridianForge** [BEL-Public/cached-property#5]
@ephathaway is having issues importing this library into a Jupyter notebook - and is getting a No module named 'cached_property' error whereas running the same import directly from the Python interpreter, has no issues.

**Comment by ephathaway** [comment]
I figured out why I was having this issue. I forgot to install jupyter in the conda environment I set up for `mffpy`, so when I launched the jupyter notebook it was calling on the jupyter installed on conda base, and so none of the required packages for `mffpy` were loaded. This turns out to not be an issue with `cached-property`.

**Comment by ViridianForge** [comment]
Ah - then we'll close this as a non-issue.  Might want to update our setup procedures around the lab though. 😄
